[package]
name = "vhost-user-rpmb"
version = "0.1.0"
authors = ["Alex Bennée <alex.bennee@linaro.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
