[package]
name = "vhost-user-rpmb"
version = "0.1.0"
authors = ["Alex Bennée <alex.bennee@linaro.org>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33.3",  features = ["yaml"] }
memmap = "0.6.2"
vhostuser_rs = { git = "https://github.com/jiangliu/vhostuser_rs" }
